#!/bin/bash

export LC_ALL=C

LIST_BOOKMARKS_FILE=~/.config/dmenu_move_bookmarks.set
UNDO_SCRIPT_FILE=~/.config/dmenu_move_undo.sh


## ------------------------------------------------------------------------
## GET CONF

SPECIAL_DESTS="UNDO"

ALIAS_LIST=$(awk '{
if (index($0,"#")==1) {}
else if (NF == 0) {}
else {print $1}
}' $LIST_BOOKMARKS_FILE)

ALIAS_LIST="${ALIAS_LIST}
${SPECIAL_DESTS}"


## ------------------------------------------------------------------------
## PROMPT

DEST_ALIAS=$(echo "$ALIAS_LIST" | dmenu -i -p "move to>" -nb black -nf white -sf red)

if [[ "$DEST_ALIAS" = "" ]]; then
    # interupted by user
    exit
fi


## ------------------------------------------------------------------------
## SPECIAL CASE: UNDO LAST MOVE

if [ "$DEST_ALIAS" = "UNDO" ]; then
    . $UNDO_SCRIPT_FILE
    cat /dev/null > $UNDO_SCRIPT_FILE
    exit
fi


## ------------------------------------------------------------------------
## RETRIEVE ASSOCIATED LOCATION

DEST_ALIAS=$(echo "$DEST_ALIAS" | sed -e 's|/|\\/|g')

DEST=$(cat $LIST_BOOKMARKS_FILE | sort -u | awk ' $0 ~ /^'$DEST_ALIAS'/ {
if (NF > 1) {$1="";print }
else { print $1 }
}' | head -1 | sed -e 's/^[ \t]*//')
# NB: last sed is for removing leading whitespaces and tabs

DEST=$(echo "$DEST" | sed -e "s|^~|$HOME|")


## ------------------------------------------------------------------------
## MOVE

if [[ ! -d "$DEST" ]]; then
    notify-send 'dmenu_move error' "dest folder $DEST not reachable"
    exit 1
fi

## Create undo script
cat /dev/null > $UNDO_SCRIPT_FILE
for file in $NAUTILUS_SCRIPT_SELECTED_URIS; do
    file=`echo $file | sed 's#file://##g' | sed 's#%20# #g' | sed 's#%C3%A9#é#g' | sed 's#%C3%A0#à#g' | sed 's#%C3%A7#ç#g' | sed 's#%C3%A8#è#g'`
    file_dir=${file%/*}
    file=${file##*/}
    echo "mv -u \"$DEST/$file\" \"$file_dir\"" >> $UNDO_SCRIPT_FILE
done

## Move them finally
for file in $NAUTILUS_SCRIPT_SELECTED_URIS; do
    file=`echo $file | sed 's#file://##g' | sed 's#%20# #g' | sed 's#%C3%A9#é#g' | sed 's#%C3%A0#à#g' | sed 's#%C3%A7#ç#g' | sed 's#%C3%A8#è#g'`
    mv -u "$file" "$DEST"
done
fi
